"""
이 폴더(chuckchuck)의 출입구 파일입니다.
밖에서 `from chuckchuck import parse_document`처럼 쓸 수 있게
주요 함수·타입을 모아 내보내 줍니다.
"""

from .config import settings
from .contracts import (
    AlignError,
    AlignmentDoc,
    AlignmentItem,
    AlignmentSummary,
    ChatterDoc,
    ChatterError,
    ChatterRef,
    ChatterTurn,
    ChuckchuckError,
    ConceptDoc,
    ConceptEdge,
    ConceptGraph,
    ConceptNode,
    Context,
    ExtraConcept,
    FlowDiff,
    FlowIssue,
    FlowStep,
    GraphError,
    HabitDoc,
    HabitError,
    HabitSpan,
    JudgeError,
    PaceDoc,
    PaceError,
    ParseError,
    QaJudgement,
    QaTriage,
    QaTurn,
    Question,
    QuestionDoc,
    QuestionError,
    ReportDoc,
    ReportError,
    RubricClusterScore,
    RubricError,
    RubricItemScore,
    RubricScore,
    STTError,
    Section,
    SlideDoc,
    SlideMark,
    SpeechBasis,
    SpeechEdge,
    Transcript,
    TriageMark,
    WeightBasis,
    WordTimestampUnsupported,
    qa_mastered,
    qa_passed,
    qa_probe_tier,
)
from .f01_parse import parse_document, sparse_slide_numbers
from .f05_stt import speech_for_slide, split_by_slide, transcribe
from .f06_concepts import extract_concepts
from .f07_graph import build_graph
from .f08_questions import build_hint_ladder, build_questions, triage_questions
from .f09_judge import coach_stuck, judge_answer, looks_stuck
from .f11_align import align_speech
from .f11_flow import build_flow_diff
from .f12_chatter import build_chatter
from .f13_score import score_presentation
from .f14_rubric import from_legacy_score, score_rubric
from .f17_pace import analyze_pace
from .f18_habits import extract_habits
from .f19_report import compose_report

__all__ = [
    "AlignError",
    "AlignmentDoc",
    "AlignmentItem",
    "AlignmentSummary",
    "ChatterDoc",
    "ChatterError",
    "ChatterRef",
    "ChatterTurn",
    "ChuckchuckError",
    "ConceptDoc",
    "ConceptEdge",
    "ConceptGraph",
    "ConceptNode",
    "Context",
    "ExtraConcept",
    "FlowDiff",
    "FlowIssue",
    "FlowStep",
    "GraphError",
    "HabitDoc",
    "HabitError",
    "HabitSpan",
    "JudgeError",
    "PaceDoc",
    "PaceError",
    "ParseError",
    "QaJudgement",
    "QaTriage",
    "QaTurn",
    "Question",
    "QuestionDoc",
    "QuestionError",
    "ReportDoc",
    "ReportError",
    "RubricClusterScore",
    "RubricError",
    "RubricItemScore",
    "RubricScore",
    "STTError",
    "Section",
    "SlideDoc",
    "SlideMark",
    "SpeechBasis",
    "SpeechEdge",
    "Transcript",
    "TriageMark",
    "WeightBasis",
    "WordTimestampUnsupported",
    "align_speech",
    "analyze_pace",
    "build_chatter",
    "build_flow_diff",
    "build_graph",
    "build_hint_ladder",
    "build_questions",
    "coach_stuck",
    "compose_report",
    "extract_concepts",
    "extract_habits",
    "judge_answer",
    "looks_stuck",
    "parse_document",
    "qa_mastered",
    "qa_passed",
    "qa_probe_tier",
    "score_presentation",
    "score_rubric",
    "from_legacy_score",
    "settings",
    "sparse_slide_numbers",
    "speech_for_slide",
    "split_by_slide",
    "transcribe",
    "triage_questions",
]

__version__ = "0.4.0"
