/**
 * 데모용 샘플 데이터(제목·이미지 등)입니다.
 * 실API 자료가 없을 때 화면을 채워 보는 용도입니다.
 */

const DATA = {
  session: {
    title: 'IMU2CLIP 논문 리뷰',
    file: '250729 IMU2CLIP_Pulbic.pdf',
    occasion: '학회·수업 발표',
    slides: 23,
    duration: '10분 18초',
    durationSec: 618,
    nth: 2,
    score: 86,
    prevScore: 76,
    dims: [['내용 이해', 84], ['논리 흐름', 82], ['말 속도', 91]],
    avgCpm: 326,
    oneLiner: '핵심 구조는 전달됐고, 질문을 거치며 공동 임베딩 정렬을 자기 말로 설명할 수 있게 됐어요.',
    qa: { before: 3, after: 5, total: 5, mastered: '공동 임베딩 정렬 · Temperature Parameter', weak: 'IMU Encoder 설명',
      trophy: { slide: 7, node: 'joint',
        before: '비디오, IMU, 텍스트를 joint space에 정렬합니다.',
        after: '같은 시간의 IMU, 영상, 문장은 같은 행동을 표현해서 가까운 벡터가 됩니다.' } },
  },

  sessions: [
    { id:'imu2clip', title: 'IMU2CLIP 논문 리뷰', occasion: '학회·수업 발표', slides: 23, date: '오늘', nth: 2, score: 86, diff: 10, note: 'Q&A로 공동 임베딩 정렬 이해' },
    { id:'vla', title: 'Hierarchical VLA 논문 리뷰', occasion: '학회·수업 발표', slides:35, date: '1월 13일', nth: 1, score: 79, diff: 8, note: '실패 데이터의 역할 보완' },
    { id:'pitch', title: '척척발표 서비스 피치', occasion: '대회·IR 피칭', slides:12, date: '1월 8일', nth: 3, score: 91, diff: 14, note: 'Q&A 5/5 통과' },
    { id:'q2-report', title: '2분기 제품 성과 보고', occasion: '사내 보고', slides:14, date: '12월 28일', nth: 5, score: 87, diff: 11, note: '시간 배분 안정적' },
    { id:'trend', title: '소비 트렌드 세미나', occasion: '학회·수업 발표', slides:18, date: '12월 21일', nth: 6, score: 68, diff: 7, note: '근거 발화 2곳 보완' },
  ],
  growth: { scores: [61, 68, 74, 79, 86], text: '최근 5회 완성도 61 → 86 · 설명 누락 4개 → 1개' },

  reportProfiles: {
    vla: {
      title:'Hierarchical VLA 논문 리뷰', occasion:'학회·수업 발표', slides:35, duration:'12분 06초', nth:1, score:79, diff:8,
      dims:[['내용 이해',81],['논리 흐름',75],['말 속도',83]], before:3, after:4, total:5,
      mastered:'실패 데이터가 필요한 이유', weak:'Weight Merging + LoRA',
      oneLiner:'VINE의 큰 구조는 전달됐지만, 두 시스템이 실제로 학습되는 연결 과정은 더 설명해야 해요.',
      evidence:[
        {status:'ok',slide:9,time:'04:18',title:'실패 데이터의 역할',quote:'“실패 시연은 버리는 데이터가 아니라 System 2가 위험을 평가하는 근거가 됩니다.”',note:'Q&A 뒤 성공·실패 혼합 데이터의 역할을 자기 말로 설명했어요.'},
        {status:'mid',slide:11,time:'06:42',title:'PaliGemma와 π0 결합',quote:'“두 모델을 합쳐서 하나의 backbone으로 사용합니다.”',note:'결합 결과는 말했지만 공유 layer를 왜 merge하는지는 빠졌어요.'},
        {status:'no',slide:12,time:'—',title:'Weight Merging + LoRA',quote:'관련 발화를 찾지 못했어요.',note:'전체 모델을 업데이트하지 않고 task head를 학습하는 이유를 한 문장으로 준비해보세요.'},
      ],
      priorities:['Weight Merging과 LoRA의 역할을 구분해서 설명하기','System 2의 평가 결과가 System 1 행동에 반영되는 흐름 연결하기','성공 데이터만 학습한 기존 VLA와 비교 문장 추가하기'],
    },
    pitch: {
      title:'척척발표 서비스 피치', occasion:'대회·IR 피칭', slides:12, duration:'6분 34초', nth:3, score:91, diff:14,
      dims:[['내용 이해',94],['논리 흐름',90],['말 속도',88]], before:4, after:5, total:5,
      mastered:'근거 기반 판정의 차별점', weak:'초기 고객 확보 전략',
      oneLiner:'문제와 해결책은 선명했고, Q&A에서 “왜 기존 발표 코치와 다른가”까지 근거로 방어했어요.',
      evidence:[
        {status:'ok',slide:3,time:'00:48',title:'사용자 문제',quote:'“자료는 완성했지만 정작 왜 그런지 설명하지 못하는 순간을 찾습니다.”',note:'타깃 사용자의 문제를 한 문장으로 분명하게 제시했어요.'},
        {status:'ok',slide:6,time:'02:31',title:'서비스 차별점',quote:'“AI 총평 대신 실제 발화와 슬라이드 위치를 모든 판정에 붙입니다.”',note:'Q&A에서 경쟁 서비스와의 차이를 근거 우선 원칙으로 설명했어요.'},
        {status:'mid',slide:10,time:'05:12',title:'Go-to-market',quote:'“대학생과 취업 준비생부터 시작할 계획입니다.”',note:'대상은 말했지만 첫 사용자를 어디서 어떻게 모을지는 부족했어요.'},
      ],
      priorities:['초기 고객 채널과 첫 100명 확보 방법 제시하기','무료 연습에서 유료 전환되는 순간 설명하기','판정 정확도 8/10 기준을 검증 계획과 연결하기'],
    },
    'q2-report': {
      title:'2분기 제품 성과 보고', occasion:'사내 보고', slides:14, duration:'9분 22초', nth:5, score:87, diff:11,
      dims:[['내용 이해',89],['논리 흐름',86],['말 속도',85]], before:4, after:5, total:5,
      mastered:'전환율 상승의 원인', weak:'3분기 리텐션 리스크',
      oneLiner:'성과 수치는 명확했고, Q&A에서 전환율 상승이 어떤 실험에서 왔는지까지 연결했어요.',
      evidence:[
        {status:'ok',slide:4,time:'01:37',title:'활성 사용자 증가',quote:'“주간 활성 사용자는 전분기보다 18% 늘었고 신규 온보딩 개선이 가장 크게 기여했습니다.”',note:'수치와 원인을 함께 제시했어요.'},
        {status:'ok',slide:8,time:'04:56',title:'결제 전환율',quote:'“무료 체험 안내를 첫날이 아니라 핵심 기능 사용 직후로 옮겨 전환율이 2.1%p 올랐습니다.”',note:'Q&A 뒤 실험 변경과 결과를 구체적으로 설명했어요.'},
        {status:'mid',slide:12,time:'07:48',title:'3분기 리스크',quote:'“리텐션은 계속 모니터링하겠습니다.”',note:'어떤 코호트와 임계값을 볼지 기준이 필요해요.'},
      ],
      priorities:['3분기 리텐션 위험 코호트와 경보 기준 제시하기','전환율 실험의 표본 크기와 기간 함께 말하기','성과에서 다음 분기 실행 항목으로 넘어가는 연결 문장 추가하기'],
    },
    trend: {
      title:'소비 트렌드 세미나', occasion:'학회·수업 발표', slides:18, duration:'11분 40초', nth:6, score:68, diff:7,
      dims:[['내용 이해',72],['논리 흐름',64],['말 속도',70]], before:2, after:4, total:5,
      mastered:'가성비와 가치소비의 차이', weak:'설문 표본 편향',
      oneLiner:'트렌드 사례는 풍부했지만, 조사 표본에서 전체 소비자로 일반화하는 근거가 약했어요.',
      evidence:[
        {status:'ok',slide:5,time:'02:14',title:'가성비와 가치소비',quote:'“가격이 싸서 고르는 것과 내 가치관에 맞아 더 지불하는 것은 다른 행동입니다.”',note:'Q&A 뒤 두 개념을 선택 기준으로 구분했어요.'},
        {status:'mid',slide:9,time:'05:22',title:'숏폼 구매 전환',quote:'“요즘은 대부분 숏폼을 보고 바로 구매합니다.”',note:'사례는 있지만 연령대와 플랫폼 범위가 빠졌어요.'},
        {status:'no',slide:14,time:'—',title:'설문 표본 편향',quote:'표본 구성에 관한 발화를 찾지 못했어요.',note:'20대 수도권 응답자가 많은 조사라는 한계를 반드시 밝혀야 해요.'},
      ],
      priorities:['설문 표본의 연령·지역 편향을 먼저 밝히기','트렌드마다 관찰 기간과 데이터 출처 붙이기','사례 나열을 세 가지 소비 동기로 묶어서 설명하기'],
    },
  },

  slideTitles: [
    'IMU2CLIP 논문 리뷰', '논문 정보', 'Self-Supervised Learning', 'Contrastive Learning', 'CLIP',
    'Motivation & Intro', 'Overall Framework', '세 가지 Contrastive Loss', 'IMU Encoder', 'IMU Encoder 구조',
    'Similarity와 Alignment Probability', 'Cross-Entropy Loss', '전체 학습 목적함수', 'Dataset: Ego4D · Aria',
    'Text → IMU Retrieval', 'IMU → Video Retrieval', 'Multimodal Alignment', 'Downstream Activity Recognition',
    'Future Work: Multimodal Reasoning', 'Contribution', 'Limitation & Points', 'Appendix', 'Appendix',
  ],
  slideImages: Array.from({ length: 23 }, (_, i) => `assets/slides/imu2clip/slide-${String(i + 1).padStart(2, '0')}.webp`),

  tree: [
    { id:'ssl', label:'Self-Supervised Learning', depth:1, w:.92, slide:'S03', status:'ok', conf:94,
      check:{정의:1,원리:1,관계:1,이유:1}, ev:'“라벨을 직접 만들지 않고 pretext task로 표현을 먼저 학습합니다.”', evTime:'1:04',
      why:'라벨 비용 문제와 pretext task의 역할을 함께 설명했어요.', fix:'이 설명 흐름을 유지하세요.' },
    { id:'contrast', label:'Contrastive Learning', depth:1, w:.91, slide:'S04', status:'mid', conf:82,
      check:{정의:1,원리:1,관계:0,이유:0}, ev:'“같은 데이터는 가깝게, 다른 데이터는 멀게 만드는 방식입니다.”', evTime:'1:48',
      why:'기본 원리는 말했지만 IMU·Video·Text 세 모달리티로 확장되는 이유가 빠졌어요.',
      fix:'세 모달리티가 같은 사건을 표현하므로 하나의 공간에서 같은 시점끼리 가깝게 학습한다고 이어보세요.' },
    { id:'clip', label:'CLIP', depth:1, w:.86, slide:'S05', status:'ok', conf:91,
      check:{정의:1,원리:1,관계:1,이유:1}, ev:'“CLIP은 이미지와 텍스트를 같은 임베딩 공간에 정렬합니다.”', evTime:'2:27',
      why:'IMU2CLIP의 출발점과 연결해서 설명했어요.', fix:'IMU가 세 번째 모달리티라는 문장을 바로 이어보세요.' },
    { id:'motivation', label:'IMU2CLIP의 동기', depth:1, w:.84, slide:'S06', status:'ok', conf:89,
      check:{정의:1,원리:1,관계:1,이유:1}, ev:'“IMU 라벨링 비용과 새로운 활동에 대한 일반화 문제가 핵심입니다.”', evTime:'3:12',
      why:'문제와 제안 방법의 관계가 분명해요.', fix:'이 흐름을 유지하세요.' },
    { id:'joint', label:'공동 임베딩 정렬', depth:2, parent:'contrast', w:.79, slide:'S07', status:'mid', conf:79,
      check:{정의:1,원리:0,관계:0,이유:1}, ev:'“비디오, IMU, 텍스트를 joint space에 정렬합니다.”', evTime:'3:56',
      why:'무엇을 하는지는 말했지만 같은 시점의 세 데이터가 왜 가까워지는지 설명하지 않았어요.',
      fix:'같은 시간 구간의 IMU·영상·문장은 같은 행동을 가리키므로 positive pair가 된다고 설명해보세요.' },
    { id:'pairs', label:'세 가지 Contrastive Pair', depth:2, parent:'contrast', w:.77, slide:'S08', status:'mid', conf:84,
      check:{정의:1,원리:1,관계:1,이유:0}, ev:'“IMU-Video, Video-Text, Text-IMU loss를 사용합니다.”', evTime:'4:28',
      why:'세 쌍은 나열했지만 왜 모두 필요한지는 설명하지 않았어요.', fix:'Video가 IMU와 Text 사이의 의미적 다리 역할을 한다고 덧붙여보세요.' },
    { id:'encoder', label:'IMU Encoder', depth:2, parent:'joint', w:.66, slide:'S10', status:'no', conf:92,
      check:{정의:0,원리:0,관계:0,이유:0}, ev:'IMU Encoder의 1D convolution·residual block 구조를 설명한 발화를 찾지 못했어요.', evTime:'',
      why:'모델이 원시 IMU 신호를 임베딩으로 바꾸는 핵심 과정이 발표에서 빠졌어요.', fix:'6축 IMU window가 1D convolution과 residual block을 거쳐 하나의 표현이 된다고 말해보세요.' },
    { id:'temp', label:'Temperature Parameter', depth:2, parent:'joint', w:.62, slide:'S11', status:'no', conf:90,
      check:{정의:0,원리:0,관계:0,이유:0}, ev:'확률식은 보여줬지만 temperature가 분포의 집중도를 조절한다는 설명은 없었어요.', evTime:'5:21',
      why:'수식의 핵심 파라미터가 청중에게 해석되지 않았어요.', fix:'temperature가 작을수록 정답 쌍에 더 뾰족하게 확률을 모은다고 풀어보세요.' },
    { id:'loss', label:'Cross-Entropy Loss', depth:2, parent:'pairs', w:.60, slide:'S12', status:'mid', conf:80,
      check:{정의:1,원리:0,관계:1,이유:0}, ev:'“양방향 cross-entropy를 평균합니다.”', evTime:'5:54',
      why:'수식은 읽었지만 양방향으로 계산하는 이유는 설명하지 않았어요.', fix:'IMU로 Video를 찾는 방향과 Video로 IMU를 찾는 방향을 모두 맞춘다고 말해보세요.' },
    { id:'aria', label:'Aria 데이터셋 해석', depth:2, parent:'pairs', w:.51, slide:'S16', status:'ct', conf:87,
      check:{정의:1,원리:1,관계:0,이유:0}, docSays:'Aria에는 text narration이 없지만 IMU-Video 정렬이 가능했어요.',
      spokeSays:'“Aria도 IMU, Video, Text 세 모달리티를 모두 제공합니다.”', spokeTime:'7:14',
      why:'자료와 발화가 달라 결과 해석을 왜곡할 수 있어요.', fix:'Aria에는 text narration이 없다는 점을 명확히 말해주세요.' },
    { id:'appendix', label:'Appendix', depth:2, w:.18, slide:'S22', status:'om', conf:96,
      check:{정의:0,원리:0,관계:0,이유:0}, ev:'발화에 없지만 본 발표에서는 생략이 자연스러워 감점하지 않았어요.', evTime:'',
      why:'핵심 주장에 영향을 주지 않는 보조 자료예요.', fix:'Q&A 대비용으로만 확인하세요.' },
  ],

  slideStatus: ['none','none','ok','mid','ok','ok','mid','mid','none','no','no','mid','none','none','ok','ct','none','none','none','ok','no','om','om'],
  slideMainNode: {3:'ssl',4:'contrast',5:'clip',6:'motivation',7:'joint',8:'pairs',10:'encoder',11:'temp',12:'loss',16:'aria',22:'appendix'},
  timeline: [
    {sec:108,time:'1:48',type:'mid',label:'세 모달리티로 확장되는 이유가 비어 있어요',tab:1,node:'contrast',onSlide:4},
    {sec:236,time:'3:56',type:'mid',label:'공동 임베딩 정렬의 원리 설명이 부족해요',tab:1,node:'joint',onSlide:7},
    {sec:300,endSec:348,time:'5:00–5:48',type:'fast',label:'수식 구간에서 본인 평균보다 24% 빨라졌어요',tab:3,onSlide:11},
    {sec:321,time:'5:21',type:'no',label:'Temperature parameter 해석이 빠졌어요',tab:1,node:'temp',onSlide:11},
    {sec:434,time:'7:14',type:'ct',label:'Aria 데이터셋 설명이 자료와 달라요',tab:1,node:'aria',onSlide:16},
    {sec:552,time:'9:12',type:'ok',label:'한계에서 future work로 자연스럽게 연결했어요',tab:2,onSlide:19},
  ],
  logicBreaks: [
    {type:'연결 멘트 없음',from:'5번',to:'7번',time:'3:36',ev:'“여기까지가 CLIP이고, 다음은 전체 구조입니다.”',note:'CLIP의 두 모달리티 정렬이 IMU까지 확장된다는 연결 문장이 필요해요.'},
    {type:'근거 점프',from:'11번',to:'12번',time:'5:38',ev:'“이 확률을 가지고 바로 loss를 계산합니다.”',note:'확률이 정답 pair를 얼마나 잘 찾는지 cross-entropy로 학습한다는 다리가 비어 있어요.'},
    {type:'잘된 연결',from:'18번',to:'19번',time:'9:12',good:true,ev:'“활동 인식을 넘어서, IMU를 언어로 바꾸면 LLM과도 연결할 수 있습니다.”',note:'실험 결과에서 future work로 자연스럽게 이어졌어요.'},
  ],
  pace: [
    ['배경',3,312],['Contrastive Learning',4,328],['CLIP',5,319],['동기',6,305],['전체 구조',7,336],
    ['세 가지 Loss',8,352],['수식',11,407,true],['실험 결과',15,344],['한계',21,318],['마무리',20,302],
  ],
  paceStats: {avg:326,max:407,maxSeg:'수식 설명',rec:'300~350'},
  timeAlloc: [
    ['배경',18,21,'+17% 초과'],['동기·구조',25,24,'적절'],['방법론',30,20,'-33% 부족'],['실험',18,23,'+28% 초과'],['한계·결론',9,12,'적절'],
  ],
  priorities: {
    '학회·수업 발표': [
      {t:'공동 임베딩 정렬을 발표 문장으로 복원하기',gain:5,d:'발표에서는 joint space라는 결과만 말했지만 Q&A를 거치며 positive pair의 이유를 설명할 수 있게 됐어요.',spoke:{text:'“같은 시간의 IMU, 영상, 문장은 같은 행동을 표현해서 가까워져야 합니다.”',time:'Q&A 04:31'},fix:'이 문장을 7번 슬라이드에서 그대로 사용해보세요.'},
      {t:'Temperature를 Q&A에서 완성한 문장으로 바꾸기',gain:4,d:'발표에서는 수식만 읽었지만, 질문 뒤에는 분포 집중도와 학습 효과를 연결했어요.',spoke:{text:'“temperature가 작을수록 정답 쌍에 확률을 더 뾰족하게 모아 구분을 강하게 학습합니다.”',time:'Q&A 06:12'},fix:'이 문장을 11번 슬라이드의 수식 아래에서 사용해보세요.'},
      {t:'Aria 데이터셋 설명 바로잡기',gain:3,d:'자료에는 text narration이 없다고 적혀 있지만 발표에서는 세 모달리티가 모두 있다고 말했어요.',spoke:{text:'“Aria도 IMU, Video, Text를 모두 제공합니다.”',time:'7:14'},fix:'“Aria에는 text가 없어도 IMU-Video 정렬이 유지됐어요.”'},
    ],
  },
  punchlines: [
    {time:'03:56',pos:'7번 슬라이드 · Overall Framework',main:'같은 순간의 움직임, 영상, 문장을 하나의 좌표에 모읍니다.',why:'Q&A에서 완성한 공동 임베딩 정렬 설명을 발표 문장으로 압축했어요.'},
    {time:'09:42',pos:'20번 슬라이드 · Contribution',main:'IMU를 단순 센서값이 아니라 검색하고 설명할 수 있는 언어로 바꿉니다.',why:'방법과 기여를 한 문장으로 연결하는 마무리예요.'},
  ],
  terms: [
    {term:'공동 임베딩 정렬',status:'mid',def:'같은 시간의 IMU·영상·문장을 가까운 벡터로 만드는 학습.',slide:'S07',q:'왜 세 모달리티를 같은 공간에 놓아야 하나요?',frame:'① 같은 사건 → ② positive pair → ③ 검색·분류 활용'},
    {term:'Temperature Parameter',status:'no',def:'유사도 확률분포가 얼마나 뾰족해질지 조절하는 값.',slide:'S11',q:'Temperature가 작아지면 학습 신호는 어떻게 달라지나요?',frame:'① 분포 집중도 → ② 정답 pair 확률 → ③ 너무 작을 때 위험'},
    {term:'양방향 Contrastive Loss',status:'mid',def:'A로 B를 찾는 방향과 B로 A를 찾는 방향을 모두 학습하는 손실.',slide:'S12',q:'한 방향 loss만 쓰면 무엇이 부족한가요?',frame:'① 두 검색 방향 → ② 비대칭 오류 → ③ 평균'},
    {term:'Aria 데이터셋',status:'ct',def:'Text narration 없이 IMU와 Video 정렬을 평가한 데이터셋.',slide:'S16',q:'Text가 없어도 정렬 성능이 나온 것이 왜 중요한가요?',frame:'① 데이터 조건 → ② 결과 → ③ 일반화 의미'},
  ],
  mapNodes: [
    {id:'r',label:'IMU2CLIP',root:true},{id:'a',label:'배경·동기',status:'ok',slide:'S03'},{id:'b',label:'공동 임베딩',status:'mid',slide:'S07'},
    {id:'c',label:'실험·한계',status:'mid',slide:'S15'},{id:'a1',label:'CLIP',status:'ok',slide:'S05',p:'a'},
    {id:'b1',label:'세 가지 Pair',status:'mid',slide:'S08',p:'b'},{id:'b2',label:'Temperature',status:'no',slide:'S11',p:'b'},
    {id:'c1',label:'Aria',status:'ct',slide:'S16',p:'c'},{id:'c2',label:'Future Work',status:'ok',slide:'S19',p:'c'},
  ],

  /* 대화형 질문 코칭 · 하나의 스레드로 이어지는 비트들 */
  qaBeats: [
    { id:'b0', kind:'ask', concept:'joint', conceptLabel:'공동 임베딩 정렬', slide:'S07',
      meta:'질문',
      basis:'“같은 데이터는 가깝게, 다른 데이터는 멀게” · 4번 슬라이드',
      q:{교수님:'자, IMU2CLIP은 왜 두 개도 아니고 세 개의 모달리티를 한 공간에 정렬하죠?',
         심사위원:'세 가지 contrastive pair를 다 쓴다고 했는데, 각각이 성능에 기여한다는 근거가 있어요?',
         '회사 상사':'시간 없으니 한 줄로. 모달리티 세 개 붙이면 — 그래서 우리가 뭘 할 수 있게 돼요?',
         '일반 청중':'움직임이랑 영상이랑 문장을 “같은 공간에 놓는다”… 그게 쉽게 말하면 무슨 뜻이에요?'},
      answer:'음, 각각 데이터가 다르니까 같이 학습하면 서로 도움이 되지 않을까요.',
      verdict:'partial',
      react:'방향은 맞아요. 근데 “도움이 된다”가 좀 두루뭉술해요. 왜 하필 가까이 붙여야 하는지가 빠졌어요.',
      by:{ '회사 상사':{ kind:'interrupt', cutAt:0.45,
        interject:'스톱. 그건 배경이고 — 결론부터요. 세 개 붙이면 우리가 “뭘” 할 수 있게 돼요?',
        answerAfter:'…아, 결론은 움직임만으로도 영상이나 문장을 검색할 수 있게 됩니다.',
        react:'그게 첫 문장이어야죠. 배경 깔지 말고 결론부터. 15초 룰 기억해요.' } } },

    { id:'b1', kind:'interrupt', concept:'joint', conceptLabel:'공동 임베딩 정렬', slide:'S07',
      meta:'파고들기',
      q:{교수님:'그럼 같은 시간에 찍힌 IMU, 영상, 문장은 왜 서로 “가까운” 벡터가 돼야 하죠?',
         심사위원:'그 정렬이 “가까워진다”는 인과, 성립한다는 근거가 있어요?',
         '회사 상사':'좋아요, 근데 왜 “가까이” 붙여야 하죠? 한마디로.',
         '일반 청중':'근데 왜 “가까워야” 하는 거예요? 시간만 같으면 다 가까운 거예요?'},
      answer:'아 그건 같은 순간에 같이 측정된 데이터라서, 시간이 같으니까 자연스럽게 가까이 붙는 거고, 그래서',
      cutAt:0.55,
      interject:'잠깐 — “시간이 같다”까지는 좋아요. 근데 시간이 같은 게 왜 “가까워야 할” 이유가 되죠? 같은 시각에 찍혔어도 서로 딴 얘길 할 수도 있잖아요.',
      answerAfter:'…그러네요. 시간이 같다고 무조건 가까운 건 아니고… 음, 왜 가까워야 하는지는 잘 모르겠어요.',
      verdict:'none',
      react:'괜찮아요, 여기서 다 막혀요. 힌트 하나 열어드릴게요.',
      by:{
        심사위원:{ interject:'“시간이 같아서”는 관찰이지 근거가 아니에요. 왜 가까워야 하는지, 인과를 대보세요.' },
        '회사 상사':{ interject:'됐고 — 왜 “가까이”가 필요해요? 결론만.' },
        '일반 청중':{ interject:'음… 근데 시간이 같으면 왜 가까워요? 그게 이해가 안 돼요.' } } },

    { id:'b2', kind:'ask', concept:'joint', conceptLabel:'공동 임베딩 정렬', slide:'S07', autoHint:1,
      meta:'비유로 다시',
      q:{교수님:'사람이 자전거를 타는 딱 한 순간을 떠올려볼게요. IMU, 영상, 문장은 그 순간을 각각 어떻게 담을까요?',
         심사위원:'구체적 예로 검증해보죠. 자전거 타는 한 순간 — 세 데이터가 정말 “같은 것”을 가리키나요?',
         '회사 상사':'예시 하나로 빠르게. 자전거 타는 순간, 세 데이터가 각각 뭘 담아요?',
         '일반 청중':'자전거 타는 장면으로 쉽게 갈게요. 그 순간을 움직임·영상·문장이 각각 어떻게 담을까요?'},
      answer:'IMU는 페달 밟는 움직임, 영상은 자전거 타는 장면, 문장은 “자전거를 탄다”고 표현합니다.',
      verdict:'partial',
      react:'바로 그거예요. 셋 다 “자전거 타기”라는 같은 행동을 가리키죠. 거의 다 왔어요.' },

    { id:'b3', kind:'ask', concept:'joint', conceptLabel:'공동 임베딩 정렬', slide:'S07', autoHint:2,
      meta:'한 문장으로',
      q:{교수님:'좋아요. 그럼 이제 공동 임베딩 정렬이 왜 필요한지, 처음부터 자기 말로 쭉 설명해볼래요?',
         심사위원:'정리해보세요. 공동 임베딩 정렬이 왜 필요한지, 처음부터.',
         '회사 상사':'자, 결론부터 한 문장. 공동 임베딩 정렬, 왜 필요해요?',
         '일반 청중':'이제 처음부터 쉽게 설명해줄래요? 공동 임베딩 정렬이 왜 필요한지.'},
      answer:'같은 시간의 IMU, 영상, 문장은 같은 행동을 표현하니까 가까운 벡터로 만들고, 다른 행동은 멀게 만들어서 검색이랑 분류에 씁니다.',
      verdict:'full', mastered:true,
      react:'완벽해요. 처음엔 “도움이 된다”였는데 지금은 이유랑 쓰임까지 나왔어요. 이건 이제 발표에 넣으셔도 돼요.',
      by:{
        심사위원:{ kind:'interrupt', cutAt:0.85,
          interject:'…거기까지. 설명은 좋아요. 근데 심사장이라면 물어요 — 그게 안 통하는 경우는요? 한계 하나 대보세요.',
          answerAfter:'센서가 흔들려 시간 정렬이 어긋나면, 같은 순간이라는 전제가 깨져서 정렬이 약해질 수 있습니다.',
          react:'그거예요. 되는 것만 말하는 사람은 많아요. 안 되는 경우까지 아는 게 진짜 방어죠.' },
        '일반 청중':{ kind:'interrupt', cutAt:0.5,
          interject:'잠깐요, “벡터”요? 그게 무슨 말이에요? 그림 그리듯 쉽게요.',
          answerAfter:'아 쉽게요 — 비슷한 행동은 지도에서 가까운 점, 다른 행동은 먼 점으로 찍는 거예요. 그래서 찾고 나누기 쉬워져요.',
          react:'아 이제 알겠어요! 그렇게 말하니 바로 이해돼요. 발표 때도 딱 그렇게요.' } } },

    { id:'b4', kind:'trap', concept:'temp', conceptLabel:'Temperature Parameter', slide:'S11',
      meta:'함정',
      claim:'Temperature 얘기 나온 김에 제가 정리해볼게요. Temperature가 <b>클수록</b> 정답 쌍에 확률이 더 뾰족하게 모입니다. 그래서 클수록 학습이 강해지죠 — 맞죠?',
      basis:'11번 슬라이드의 γ는 확률분포의 concentration을 조절해요.',
      wrong:'네, 맞아요', right:'아니요, 반대예요',
      onWrong:'아쉬워요, 반대예요. 작을수록 분포가 정답 쌍에 뾰족하게 모여요. 이런 게 심사장에서 훅 들어옵니다.',
      onRight:'정확해요. 작을수록 뾰족해지죠. 방금 건 제가 일부러 뒤집어 말한 건데, 안 넘어가셨네요.',
      by:{ '회사 상사':{ claim:'빠르게 갈게요. Temperature <b>클수록</b> 정답에 확률이 더 뾰족하게 모인다 — 맞아요, 틀려요?' },
           '일반 청중':{ claim:'제가 들은 걸로는요, 숫자를 <b>키울수록</b> 정답을 더 콕 집는다던데 — 맞아요?' } } },

    { id:'b5', kind:'ask', concept:'temp', conceptLabel:'Temperature Parameter', slide:'S11',
      meta:'한 문장으로',
      q:{교수님:'좋아요. 그럼 Temperature가 작아질 때 분포와 학습이 어떻게 달라지는지, 이번엔 직접 한 문장으로 설명해볼래요?',
         심사위원:'Temperature가 작아질 때 분포와 학습이 정확히 어떻게 달라지죠?',
         '회사 상사':'Temperature 작아지면 어떻게 되는지, 한 문장으로.',
         '일반 청중':'그 숫자를 줄이면 무슨 일이 벌어지는지 쉽게 설명해줄래요?'},
      answer:'temperature가 작을수록 정답 쌍에 확률을 더 뾰족하게 모아서, 정답과 오답을 더 강하게 구분하도록 학습합니다.',
      verdict:'full', mastered:true,
      react:'그거예요. 수식이 아니라 “왜”로 설명하셨어요. Temperature, 이제 방어됩니다.' },

    { id:'b6', kind:'review', concept:'joint', conceptLabel:'공동 임베딩 정렬', slide:'S07',
      meta:'다시 만났어요',
      basis:'조금 전에 스스로 만든 설명이 시간이 지나도 나오는지 볼게요.',
      q:{교수님:'잠깐, 딴 얘기하다 갑자기 — 아까 공동 임베딩으로 돌아가서요. 10초 안에, 왜 필요한지 다시 설명해볼래요?',
         심사위원:'아까 공동 임베딩, 다시. 시간이 지나도 같은 논리로 방어되나요? 10초.',
         '회사 상사':'아까 그거 한 번 더. 공동 임베딩, 10초 안에 결론부터.',
         '일반 청중':'아까 그거 다시 한 번만요. 공동 임베딩, 쉽게 10초로.'},
      answer:'같은 순간의 IMU, 영상, 문장은 같은 행동의 다른 표현이라 가까이 두고, 다른 행동은 멀리 둬서 검색과 분류에 씁니다.',
      verdict:'full', reviewed:true,
      react:'식은 죽 먹기죠? 시간이 지나도 나오면 그건 진짜 아는 거예요.' },

    { id:'b7', kind:'ask', concept:'aria', conceptLabel:'Aria 일반화', slide:'S16',
      meta:'자료와 대조',
      basis:'발표자료: “Aria에는 text narration이 없지만 IMU-Video 정렬이 가능했다”',
      q:{교수님:'Text가 없는 Aria에서도 성능이 나왔다는 게, 왜 중요하죠?',
         심사위원:'Aria엔 text narration이 없는데 결과가 나왔다 — 이걸 근거로 뭘 주장할 수 있죠?',
         '회사 상사':'Aria에서 text 없이도 됐다는데, 그래서 그게 우리한테 왜 중요해요?',
         '일반 청중':'Aria에는 글자 설명이 없었는데도 됐대요. 그게 왜 대단한 거예요?'},
      answer:'Aria도 IMU, 영상, 텍스트 세 개를 다 주니까, 똑같이 정렬한 거라 자연스러운 결과입니다.',
      verdict:'none',
      react:'어, 잠깐만요. 발표자료엔 Aria에 text narration이 “없다”고 적혀 있는데요. 방금 세 개 다 있다고 하셨어요. 자료랑 다르게 말한 거예요.' },

    { id:'b8', kind:'ask', concept:'aria', conceptLabel:'Aria 일반화', slide:'S16', offerConcede:true,
      meta:'한 번 더',
      q:{교수님:'그럼 text가 없는데도 결과가 나왔다는 건, 어떤 의미일까요?',
         심사위원:'다시. text 없이 나온 결과가 “일반화”의 근거가 되려면, 뭘 보여야 하죠?',
         '회사 상사':'한 문장으로. text 없이도 됐다 = 우리한테 무슨 의미예요?',
         '일반 청중':'다시 쉽게요. 글자 없이도 됐다는 게 결국 무슨 뜻일까요?'},
      answer:'음… text 없이도 되니까… 그냥 데이터가 많아서 그런 것 같기도 하고… 잘 모르겠어요.',
      verdict:'none',
      react:'아직 흐릿하네요. 여기서 더 붙잡아도 되고, 오늘은 접고 다음 발표 숙제로 남겨도 돼요. 어떻게 할래요?',
      pushAnswer:'text가 없어도 IMU와 영상만으로 정렬이 유지됐다는 거니까, 새로운 센서 환경에도 일반화된다는 증거입니다.',
      onPush:'그거예요. 끝까지 밀어붙이니 나오네요. 이게 심사장에서 이기는 태도예요.',
      onConcede:'좋아요, 솔직한 게 나아요. 모르는 걸 아는 척하는 게 제일 위험하거든요. 리포트에 “다음에 방어할 것”으로 남길게요.' },
  ],
  qaHints: [
    '세 데이터는 같은 시간에 수집됐어요. 셋이 공통으로 “가리키는” 게 뭘까요?',
    'IMU는 움직임, 영상은 장면, 문장은 의미. 셋은 같은 무엇의 다른 얼굴일까요?',
    '같은 행동은 가깝게, 다른 행동은 멀게 둔 다음 — 그걸로 뭘 할 수 있죠?',
  ],

  /* 개념이 해소될 때 스트림·세리머니에 실시간으로 적히는 총평 문장 */
  qaSummaries: {
    joint: {
      won: '발표에서는 “joint space에 정렬한다”는 결과만 말했지만(3:56 · 7번 슬라이드), 대화에서 같은 행동이 positive pair가 되는 이유까지 자기 말로 설명했어요.',
      review: '시간이 지난 뒤에도 공동 임베딩 정렬을 같은 논리로 다시 설명했어요. 최종 이해로 확정해요.',
    },
    temp: {
      won: '발표에서는 수식만 읽었지만(5:21 · 11번 슬라이드), 질문 뒤에는 분포 집중도와 학습 효과를 연결해 설명했어요.',
    },
    aria: {
      won: '자료와 어긋났던 Aria 설명(7:14 · 16번 슬라이드)을 “text 없이도 정렬 유지 = 일반화 근거”로 바로잡았어요.',
      lost: '자료와 어긋난 Aria 설명(7:14 · 16번 슬라이드)을 확인했고, 본인 선택으로 다음 발표에서 방어할 항목으로 남겼어요.',
    },
  },
};

const STATUS = {ok:'설명함',mid:'언급만 함',no:'안 나옴',ct:'자료와 모순',om:'정당한 생략',fast:'빨라짐',none:'핵심 개념 없음'};
